### PR TITLE
Additional clarity around S3/AWS setup in README

### PR DESCRIPTION
**Pull request by eprothro**
@coderanger I think this might help those onboarding, without necessarily prescribing a specific implementation. re: #33

### CODE REVIEW

**Comment by coderanger** [comment]
As I said, I don't want to make more concrete recommendations than already present. I realize this makes usage more difficult but unfortunately this is required as you need to think through your own threat model.

**Comment by coderanger** [comment]
More to the point, this directly contradicts the suggestion already present, so you're not even following the guidance I do provide.

**Comment by eprothro** [comment]
In my opinion, an example helps new users to understand better how to think about that their threat model in the context of their application.

To your point, I am trying to follow the guidance provided, if I'm failing to do so I'm probably not the only one for which that would be true?

I'm trying to help ease adoption by sharing my experience onboarding. I defer to you as the author, of course.

**Comment by coderanger** [comment]
The layout I recommend is much flatter than what you have. No deep nesting, just a single layer of "folders" at the root of the bucket. The goal is not to create a taxonomy of secrets, but instead just to label them.

**Comment by eprothro** [comment]
Very helpful, thanks. I took "identical security requirements" in a more 'role' based way than intended.

So, in your recommendation, if there are 10 secrets, and a particular instance should have access to 4 of them, there should be 4 resources granted via IAM.

**Comment by coderanger** [comment]
Assuming those 4 aren't super directly related (though you wouldn't put a username in a secrets system since usernames are definitionally not secret, so this would be things like a service that needs two private keys for different hostname or something), probably yes. It results in a more verbose IAM policy, but that is somewhat unavoidable given the overall restrictions. Fancy policy magic is the one place where involving KMS becomes valuable since it has some policy conditional stuff that allows writing more interesting dynamic policies. I probably won't add KMS support here, but it is planned for the great secrets reckoning along with SSM support for that reason.

**Comment by eprothro** [comment]
Extremely helpful, thank you. https://github.com/eprothro/citadel/tree/documentaiton has an updated README reflecting some of the clarifications mentioned here, if you think it would help others.  

"Flat S3 structure and verbose policy" is not what I immediately picked up with the current verbiage, I think an example helps illustrate the concept, helping people think down that line, without prescribing precisely how they do it.

**Pull request closed without merging**
