### PR TITLE
Use AWS SDK instead of hand-crafting API requests

### PR DESCRIPTION
**Pull request by Fodoj**
Besides significantly reducing the size of code base, switching to AWS SDK solves two problems:

- Lack of  v4 auth (https://github.com/poise/citadel/issues/28)
- Inability to use assumed roles

Also added metadata.rb, so it's possible to use master branch from Berkshelf.

### CODE REVIEW

**Comment by coderanger** [comment]
The problem is that it also breaks using this anywhere before compile time as the gem install won't happen in time. We added `gem` dependencies in Chef for this kind of situation but the feature is too new for me to use still. As for the metadata.rb, this is not a cookbook, it is a gem. You can find a guide on using halite gems from git in the halite readme.

**Comment by coderanger** [comment]
Going to close this out as this isn't a viable direction for another 6-8 months. One option for an interim solution might be to conditionally use the new `gem` feature and then use either the internal client of aws-sdk depending on what is available at runtime. I would have to think through the ramifications of that though.

**Comment by Fodoj** [comment]
> The problem is that it also breaks using this anywhere before compile time as the gem install won't happen in time. 

Can you elaborate on this, please? I didn't quite get it.

**Comment by Fodoj** [comment]
Also, what is this new `gem` feature? Where I can read more about it?

**Comment by coderanger** [comment]
If you tried to use this helper from, say, an `attributes/default.rb` file it would fail because those are loaded before recipe code. See https://coderanger.net/two-pass/ for an overview of the loading process. As for the new gem metadata, it's in the normal docs for metadata.rb: https://docs.chef.io/config_rb_metadata.html

**Pull request closed without merging**
